# docker-compose file for development with django and vue.js running directly on the host
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      # we run redis on a non-standard port to avoid collision with a locally installed postgres
      - "6380:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: unsafe
    volumes:
      - ./data/postgres_dev:/var/lib/postgresql/data
    ports:
      # we run postgres on a non-standard port to avoid collision with a locally installed postgres
      - 5433:5432
