version: "2.1"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis.conf

  stormnotes:
    image: registry.fotcorn.ch/stormnotes/stormnotes:latest
    environment:
      - "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      - "DJANGO_SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_ALLOWED_HOSTS=${DOMAIN}"
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - stormnotes
    environment:
      - "DOMAIN=${DOMAIN}"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    restart: unless-stopped
