version: "2.1"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis.conf

  stormnotes:
    image: registry.home.9a.io/stormnotes/stormnotes
    environment:
      - "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      - "DJANGO_SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_ALLOWED_HOSTS=*"
      - "REDIS_URL=redis://redis:6379"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./uploads/:/uploads
